# Generated by Django 3.2.5 on 2021-08-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('trainline', models.CharField(max_length=50)),
                ('arrivetime', models.IntegerField()),
                ('trainnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdet', models.CharField(max_length=50)),
                ('enddet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subwaynum', models.IntegerField()),
                ('subwaysta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('userpw', models.CharField(max_length=50)),
            ],
        ),
    ]
