# Generated by Django 3.2.5 on 2021-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_beacon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='naviroot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startline', models.CharField(max_length=50)),
                ('startwname', models.CharField(max_length=50)),
                ('startwcode', models.IntegerField()),
                ('exchaline', models.CharField(max_length=50)),
                ('exchawname', models.CharField(max_length=50)),
                ('exchawcode', models.IntegerField()),
            ],
        ),
    ]
