# Generated by Django 3.2.5 on 2021-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_beacon', '0002_naviroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='waycode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
