# Generated by Django 3.2.5 on 2021-09-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_beacon', '0003_arrival_waycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='subwayim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substa', models.CharField(max_length=50)),
                ('subid', models.IntegerField()),
            ],
        ),
    ]
