# Generated by Django 3.2.5 on 2021-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_beacon', '0006_ocrimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimg',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
